POST http://localhost:5000/api/users
Content-Type: application/json

{
  "firstName":"Jane",
  "lastName": "Dou",
  "email":"m61133@m.com",
  "passwordHash": "123",
  "birthday":"1990-12-01",
  "gender":"female"
}

###

GET http://localhost:5000/api/users?page=2&results=5

### 200

GET http://localhost:5000/api/users/12

### 404

GET http://localhost:5000/api/users/111

### 200

DELETE http://localhost:5000/api/users/15

### 404

DELETE http://localhost:5000/api/users/111

### 200

PATCH  http://localhost:5000/api/users/7
Content-Type: application/json

{
    "passwordHash": "newpas2332sw"
}

### 404

PATCH  http://localhost:5000/api/users/12
Content-Type: application/json

{
    "lastName": "Newdou"
}

### 500 (422)

PATCH  http://localhost:5000/api/users/12
Content-Type: application/json

{
    "firstName": "545153153"
}



PUT http://localhost:5000/api/users/16
Content-Type: application/json

{
  "firstName":"Jane",
  "lastName": "Dou",
  "email":"m99@m.com",
  "passwordHash": "123",
  "birthday":"1990-12-01",
  "gender":"female"
}


PUT http://localhost:5000/api/users/1000
Content-Type: application/json

{
  "firstName":"Jane",
  "lastName": "Dou",
  "email":"m102@m.com",
  "passwordHash": "123",
  "birthday":"1990-12-01",
  "gender":"female"
}

### 200

GET http://localhost:5000/api/users/14/tasks 

### 200 - []

GET http://localhost:5000/api/users/1000/tasks 

### 404

GET http://localhost:5000/api/users/111/tasks 